modules/dashboard/models/BugReport.php
<?php
/*
 * This file is part of EBS-Core Breeding.
 *
 * EBS-Core Breeding is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * EBS-Core Breeding is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
* Model class for bug report widget
*/

namespace app\models;
namespace app\modules\dashboard\models;


use Yii;
use app\modules\dashboard\models\Metrics;
use yii\data\SqlDataProvider;
use app\models\Application;
use ChromePhp;

class BugReport
{

}

modules/dashboard/controllers/BugReportController.php
<?php
/*
 * This file is part of EBS-Core Breeding.
 *
 * EBS-Core Breeding is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * EBS-Core Breeding is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace app\modules\dashboard\controllers;

use Yii;
use yii\web\Controller;
use app\controllers\Dashboard;
use app\modules\dashboard\models\BugReport;

use yii\web\Request;
use app\models\User;
use yii\web\UploadedFile;
use app\components\B4RController;
use app\modules\dashboard\models\MultipleUploadForm;

/**
 * Contains methods for bug report tool
 */
class BugReportController extends B4RController
{
    /**
    * Renders bug report page
    *
    */
    public function actionIndex($program = ''){
        //use dashboard layout
        $this->layout = '@app/views/layouts/dashboard';
   
        $userModel = new User();
        $userId = $userModel->getUserId();
        $url = Yii::$app->request->referrer;
        $parsedUrl = explode('?',$url);
        $yii2Url = $parsedUrl[0];
        $yii1Url = $yii2Url;

        //if no logged in user
        if($userId == 0) {
            $email = null;
        }else{
            $email = User::getUserInfo('email');
        }
        
        $type = [
            [
                'id' => 'bug',
                'display_name' => 'Bug'
            ],
            [
                'id' => 'new_feature',
                'display_name' => 'New Feature'
            ],
            [
                'id' => 'improvement',
                'display_name' => 'Improvement'
            ],
            [
                'id' => 'inquiry',
                'display_name' => 'Inquiry'
            ],
            [
                'id' => 'data_curation',
                'display_name' => 'Data Curation and Content'
            ]
        ];
        $type = json_encode($type);
        $form = new MultipleUploadForm();
        return Yii::$app->controller->render('@app/modules/dashboard/views/bug-report/index.php',[
            'email' => $email,
            'type' => $type,
            'yii1Url' => $yii1Url,
            'yii2Url' => $yii2Url,
            'uploadForm' => $form,
            'renderedInYii1' => true
        ]);
    }

    /**
    * Renders bug report widget
    *
    */
    public function actionLoadfields($program = ''){
        $url = parse_url(Yii::$app->request->referrer);
        $userModel = new User();
        $userId = $userModel->getUserId();
        $yii2Url = $_POST['yii2url'];

        if(isset($url['query'])){
            $idxUrl = $url['path'].'?'.$url['query'];
        } else  $idxUrl = $url['path'];

        

        if(isset(Yii::$app->session['userId-'.$userId.'-program-'.$program][$idxUrl]) && Yii::$app->session['userId-'.$userId.'-program-'.$program][$idxUrl] != null){
            $yii1Url = Yii::$app->session['userId-'.$userId.'-program-'.$program][$idxUrl];
        } else { 
            $yii1Url = $yii2Url;
        }

        //if no logged in user
        if($userId == 0) {
            $email = null;
        }else{
            $email = User::getUserInfo('email');
        }

        $type = [
            [
                'id' => 'bug',
                'display_name' => 'Bug'
            ],
            [
                'id' => 'new_feature',
                'display_name' => 'New Feature'
            ],
            [
                'id' => 'improvement',
                'display_name' => 'Improvement'
            ],
            [
                'id' => 'inquiry',
                'display_name' => 'Inquiry'
            ],
            [
                'id' => 'data_curation',
                'display_name' => 'Data Curation and Content'
            ]
        ];
        $type = json_encode($type);
        $form = new MultipleUploadForm();
        return Yii::$app->controller->renderAjax('@app/modules/dashboard/views/bug-report/index.php',[
            'email' => $email,
            'type' => $type,
            'yii1Url' => $yii1Url,
            'yii2Url' => $yii2Url,
            'uploadForm' => $form
        ]);
    }

    /**
     * Creates feedback issue
     * 
     */
    public function actionCreateIssue(){
        if($_POST['request_type'] != NULL){
            $requestArr=[
                'bug'=>5,
                'new_feature'=>6,
                'improvement'=>8,
                'inquiry'=>4,
                'data_curation'=>9
            ];
            $request_type = $requestArr[$_POST['request_type']];
        } else{
            $request_type = 0;
        }
        $reporter = $_POST['reporter'];
        $summary = $_POST['summary'];
        $description = $_POST['description']."

            Yii1 URL: ".$_POST['yii1Url']."
            Yii2 URL: ".$_POST['yii2Url']." 
        ";
        $dataArr =[ 
                'serviceDeskId'=>'1', 
                'requestTypeId'=>$request_type, 
                'requestFieldValues'=> [ 
                    'summary' => $summary, 
                    'description'=> $description, 
                ],
                'raiseOnBehalfOf' => $reporter
        ]; 

        $dataStr = json_encode($dataArr); 

        $curl = curl_init(); 
        curl_setopt_array($curl, array( 
            CURLOPT_URL => 'https://riceinfo.atlassian.net/rest/servicedeskapi/request', 
            CURLOPT_RETURNTRANSFER => true, 
            CURLOPT_ENCODING => "", 
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => $dataStr, 
            CURLOPT_USERPWD => getenv('JIRA_EMAIL'). ':' . getenv('JIRA_PWD'),
            CURLOPT_HTTPHEADER => array(
                "Accept: application/json", 
                "Content-type: application/json",
            ), 
        )); 

        $output = curl_exec($curl); 
        $err = curl_error($curl); 
 
        curl_close($curl); 
         
        if ($err) { 
            Yii::$app->session->setFlash('error', '<i class="fa fa-times"></i> Failed to create the issue. '.$err );
            echo json_encode('error');
        }
        $decodedOut = json_decode($output, false); 
        
        
        $issueKey = $decodedOut->issueKey; 
        $webLink = $decodedOut->_links->web;

        Yii::$app->session->setFlash('success', '<i class="fa fa-check"></i> Your feedback has been successfully sent. View the details <b><a id="issue-link" href="'.$webLink.'" target="_blank">here.</a></b>');
        echo json_encode($issueKey);
    }

    /**
     * Creates the attachment for the initially created feedback issue
     * @param string $issueKey key of the issue created
     */
    public function actionUploadAttachment($issueKey=''){
        //copy temporary uploaded files
        $attachmentArr = [];
        if (isset($_GET['files']) && isset($_FILES)) {
            $files = $_FILES;
            if(!empty($_FILES)){
                foreach ($files as $key=>$value) {
                    $fileName  = preg_replace('/\s+/', '_', $files[$key]['name']);
                    $sourcePath = $files[$key]['tmp_name'];
                    $targetPath =  Yii::getAlias('@webroot').'/files/attachments/'.$fileName;
                    copy($sourcePath, $targetPath);
                    chmod($targetPath, 0777);
                    $attachmentArr[]=$targetPath;
                }
            }
        }

         $target_url = 'https://riceinfo.atlassian.net/rest/api/2/issue/'.trim($issueKey, '"').'/attachments';   
         
        foreach($attachmentArr as $file){
            //Initialise the cURL var 
            $ch = curl_init();     
            $data = array( 
                'file' => curl_file_create($file), 
            ); 
            
            curl_setopt_array($ch, array( 
                CURLOPT_URL => $target_url, 
                CURLOPT_RETURNTRANSFER => true, 
                CURLOPT_FOLLOWLOCATION => true, 
                CURLOPT_USERPWD => getenv('JIRA_EMAIL'). ':' . getenv('JIRA_PWD'),
                CURLOPT_VERBOSE => 1, 
                CURLOPT_POST => 1, 
                CURLOPT_HTTPHEADER => array( 
                    "Content-Type: multipart/form-data", 
                    "X-Atlassian-Token : nocheck", 
                ), 
                CURLOPT_POSTFIELDS => $data, 
            )); 
            
            $err = curl_error($ch); 
    
            curl_close($ch); 
            
            if ($err) { 
                Yii::$app->session->setFlash('error', '<i class="fa fa-times"></i> Problem attaching the file. '.$err );
                echo json_encode('error');
            }
            chmod($file, 0777);
            unlink($file);
  
        }
         echo json_encode("OK"); 
    }
}

modules/dashboard/views/bug-report/index.php
<?php
/*
 * This file is part of EBS-Core Breeding.
 *
 * EBS-Core Breeding is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * EBS-Core Breeding is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with EBS-Core Breeding.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Renders bug report widgets modal
 *
 */
use app\controllers\SiteController;
use yii\helpers\Html;
use kartik\select2\Select2;
use yii\helpers\Url;
use kartik\widgets\FileInput;
use kartik\widgets\ActiveForm;
?>
    <div id="loading-text">
    </div>
    <div class="col s12">
   
      <div class="row row-small">
        <div class="input-field col s12">
          <input id="summary_text" type="text" class="validate" data-length="80">
          <label for="summary_text" ><?=Yii::t('app', 'Summary')?> *</label>
        </div>

       
      </div>
    <div class="row row-small">
        <div class="input-field col s12">
            <textarea id="description_text" class="materialize-textarea validate" ></textarea>
            <label for="description_text" ><?=Yii::t('app', 'Description')?> *</label>
        </div>
      </div>
        <div class="row row-small">
            <div class="input-field col s6">
                <input id="reporter_field" type="text" class="validate" <?= (!empty($email)) ? 'readonly disabled' : '' ?> >
                <label class="active" for="reporter_field" style="transform: translateY(-14px) scale(0.8);transform-origin: 0 0;"> <?=Yii::t('app', 'Reporter email address')?> *</label>
            </div>
            <div class="col s6">
                <?php
                    
                    echo '<label class="control-label">'.\Yii::t('app', 'Request type').'</label>';
                    echo Select2::widget([
                        'name' => 'bug_request_type_id',
                        'id' => 'bug_request_type_id',
                        // 'data' => $data,
                        'options' => [
                            'placeholder' => 'Select request type',
                            'tags' => true,
                        ]
                    ]);
                ?>
            </div>
            
        </div>
    </div>
        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]);?>
            <!-- <form> -->
            <div class="file-field input-field">
            <div class="btn">
                <span>Attachment</span>
                <input name="file_attachment" id="report_attachment_id" type="file" multiple>
            </div>
            <div class="file-path-wrapper">
                <input class="file-path validate" id="report_attachment_id_btn"  type="text" placeholder="Attach one or more files">
            </div>
            </div>

            <?php ActiveForm::end(); ?>
    <?php if(isset($renderedInYii1)){ ?>
        <a id="bug-report-create-btn" class="btn btn-primary waves-effect waves-light pull-right" href="#" url="#"><?= \Yii::t('app', 'Submit') ?><em class="material-icons right">send</em></i></a>
    <?php } ?>

    
            


<?php
$createIssue =  Url::to(['bug-report/create-issue']);
$uploadAttachment =  Url::to(['bug-report/upload-attachment']);
$this->registerJsFile("@web/js/materialize.min.js", [
    'depends' => [\macgyer\yii2materializecss\assets\MaterializeAsset::className()],
 ], 'materialize');
$this->registerJs(<<<JS
    $("document").ready(function(){
        //enable submit button when send feedback modal is opened
        $('#bug-report-btn').on('click',function(){ 
            $('#bug-report-create-btn').removeAttr('disabled');
        });

        $('selector').select2();
        $('#bug_request_type_id').trigger('click');
        $("#bug_request_type_id").get(0).options.length = 0;
        //populate request type select 2
        var option = JSON.parse('$type');
        var s1 = document.getElementById('bug_request_type_id');
        for(var i=0; i<option.length;i++){
            var newOption = document.createElement("option");
            newOption.value = option[i]['id'];
            newOption.innerHTML = option[i]['display_name'];
            s1.options.add(newOption);
        }

        //if user not yet logged in, set inquiry as default request type
        var email = '$email';
        if(email == ''){
            $('#bug_request_type_id').val('inquiry');
        }

        //check if valid email
        function validateEmail(email) {

            filter = /^[\w-]+(\.[\w-]+)*@([a-z0-9-]+(\.[a-z0-9-]+)*?\.[a-z]{2,6}|(\d{1,3}\.){3}\d{1,3})(:\d{4})?$/;
            if (filter.test(email)) {
              // Yay! valid
              return true;
            }
            else
              {return false;}
        }

        $("#reporter_field").val('$email');

        $('#bug-report-create-btn').unbind().bind('click',function(){
            var reporter = $("#reporter_field").val();
            var summary = $("#summary_text").val();
            var description = $("#description_text").val();
            var request_type = $("#bug_request_type_id").val();

            var emailValid = validateEmail(reporter);
            $('#reporter_field').removeClass('invalid');
            
            var missingFlag = 0;
            if(reporter == '' || reporter == null || reporter == undefined ){
                $("#reporter_field").addClass('invalid');
                missingFlag = 1;
            }
            if(summary == '' || summary == null || summary == undefined ){
                $("#summary_text").addClass('invalid');
                missingFlag = 1;
            }
            if(description == '' || description == null || description == undefined ){
                $("#description_text").addClass('invalid');
                missingFlag = 1;
            }
            if(request_type == '' || request_type == null || request_type == undefined ){
                $("#bug_request_type_id").addClass('invalid');
                missingFlag = 1;
            }
           
            var files = $("#report_attachment_id")[0].files;
            var data = new FormData();
            jQuery.each(files, function(i, file) {
                data.append(i, file);
            });

            //if with missing required fields and invalid email address
            if(!emailValid && missingFlag == 1){
                $('#reporter_field').addClass('invalid');
                $('#loading-text').html('<br/><span class="red-text text-darken-2">Please specify valid email address and required fields.</span>');
            }
            else if(!emailValid){
                $('#reporter_field').addClass('invalid');
                $('#loading-text').html('<br/><span class="red-text text-darken-2">Please specify valid email address.</span>');
            }
            else if(missingFlag == 0){
                $("#bug_request_type_id").attr('disabled', 'disabled');
                $("#reporter_field").attr('disabled', 'disabled');
                $("#summary_text").attr('disabled', 'disabled');
                $("#description_text").attr('disabled', 'disabled');
                $("#report_attachment_id").attr('disabled', 'disabled');
                $("#bug-report-create-btn").attr('disabled', 'disabled');
                $('#loading-text').html('<br/><span class="teal-text text-darken-2"><i id="loading-text">Submitting feedback...</i></span><div class="progress"><div class="indeterminate"></div></div>');
                setTimeout(function(){
                    $.ajax({ 
                        url: '$createIssue', 
                        type: 'POST', 
                        data: { 
                            reporter: reporter,
                            summary: summary,
                            description: description,
                            request_type: request_type,
                            yii1Url: '$yii1Url',
                            yii2Url: '$yii2Url',
                        }, 
                        async: false, 
                        success: function(issueKey) { 
                            if(files.length > 0 && issueKey != 'error'){
                                $.ajax({ 
                                    url: '$uploadAttachment'+'?files&issueKey='+issueKey, 
                                    type: 'POST', 
                                    data:data,
                                    processData: false,
                                    contentType: false,
                                    success: function(data) { 
                                        location.reload();        
                                    }, 
                                    error: function(){ 
                                        $('.bug-report-modal-body').html('<i>There was a problem while loading content.</i>');  
                                    } 
                                });    
                            } else {
                                location.reload();
                            }
                                
                        }, 
                        error: function(){ 
                            $('.bug-report-modal-body').html('<i>There was a problem while loading content.</i>');  
                        } 
                    });
                }, 500);

            } 
            else {
                $('#loading-text').html('<br/><span class="red-text text-darken-2">Please specify the required fields.</span>');
            }
        });
    });
JS
);
?>
<style>
.collapsible span.badge {
    margin-top: 0;
}
html{
    width: 98%;
}
</style>